#!/usr/bin/env bash
# configuring domain zone so that subdomain www points to my load balancer

display_info () {
	my_script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2 $my_script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}
if [ "$#" -eq 2 ]
then
	display_info "$1" "$2"
else
	subdomain=("www" "Ib-01" "web-01" "web-02")
	for x in "${subdomain[@]}"
	do
		display_info "$1" "$x"
	done
fi
