#!/usr/bin/env bash
# install nginx web server

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
