#!/usr/bin/env bash
#Display "Best School" 10 times and "hi" on 9th iteration

i=1
while [ $i -lt 10 ]
do
	echo $"Best School"
	((i++))
	if [ $i -eq 9 ]
	then
		echo $"Best School"
		echo $"Hi"
	fi
done
