#!/usr/bin/env bash
#Displays the time for 12hrs and 59min

hour=0
while [ $hour -lt 12 ]
do
	echo "Hour: $hour"
	minute=1
	while [ $minute -lt 60 ]
	do
		echo $minute
		((minute++))
	done
	((hour++))
done
	
