#!/usr/bin/env bash
# configure an ubuntu server

cp /etc/hosts ~/hosts.new
sed -i 's/.*localhost/127.0.0.2/g' ~/hosts.new
sed -i 's/.*facebook.com//g' ~/hosts.new
sed -i '1 a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
